CREATE TABLE app_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id     BIGINT                                  NOT NULL,
    order_id       BIGINT                                  NOT NULL,
    quantity       BIGINT                                  NOT NULL,
    purchase_price DECIMAL                                 NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    order_status VARCHAR(255)                            NOT NULL,
    user_id      BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE product_audit_entries
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT                                  NOT NULL,
    product_name   VARCHAR(255)                            NOT NULL,
    price          DECIMAL                                 NOT NULL,
    stock          BIGINT                                  NOT NULL,
    operation_type VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    product_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_audit_entries PRIMARY KEY (id)
);

CREATE TABLE products
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    price DECIMAL                                 NOT NULL,
    stock BIGINT                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE revoked_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_revoked_tokens PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_role_mappings
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role_mappings PRIMARY KEY (user_id, role_id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_username UNIQUE (username);

ALTER TABLE products
    ADD CONSTRAINT uc_products_name UNIQUE (name);

ALTER TABLE revoked_tokens
    ADD CONSTRAINT uc_revoked_tokens_token_hash UNIQUE (token_hash);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE product_audit_entries
    ADD CONSTRAINT unique_product_audit_entries_product_id_version UNIQUE (product_id, version);

CREATE INDEX idx_revoked_tokens_expires_at ON revoked_tokens (expires_at);

CREATE INDEX idx_revoked_tokens_token_hash ON revoked_tokens (token_hash);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_audit_entries
    ADD CONSTRAINT FK_PRODUCT_AUDIT_ENTRIES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_audit_entries
    ADD CONSTRAINT FK_PRODUCT_AUDIT_ENTRIES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE user_role_mappings
    ADD CONSTRAINT FK_USER_ROLE_MAPPINGS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_role_mappings
    ADD CONSTRAINT FK_USER_ROLE_MAPPINGS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);