CREATE TABLE order_audit_entries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT                                  NOT NULL,
    operation  VARCHAR(255)                            NOT NULL,
    snapshot   JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_audit_entries PRIMARY KEY (id)
);

ALTER TABLE order_audit_entries
    ADD CONSTRAINT unique_order_audit_entries_order_id_version UNIQUE (order_id, version);

ALTER TABLE order_audit_entries
    ADD CONSTRAINT FK_ORDER_AUDIT_ENTRIES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_audit_entries
    ADD CONSTRAINT FK_ORDER_AUDIT_ENTRIES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);